### ISSUE TITLE
Migration path?

### ISSUE THREAD

**Issue by themouette** [point-source/supabase-tenant-rbac#14]
I'd love to use this package in my supabase application, but since several issues mention improvements (invite system for instance), I'm wondering if there will be a migration path.

If not, what would be the strategy for me to adopt?

**Comment by point-source** [comment]
Yes. Now that this is packaged as a TLE, additional improvements are easy to migrate to simply by upgrading the TLE.

Especially things like the invite system as that is purely a function and table add and does not modify the existing functionality or structure.

**Comment by themouette** [comment]
Thanks for your answer.
Let's imagine I have the v0.0.1 installed, how can I upgrade to v0.0.2 without deleting the data?

I'm a bit confused since it looks like it recreates everything from scratch.

**Comment by point-source** [comment]
I actually have the [very same question](https://github.com/point-source/supabase-tenant-rbac/issues/2#issuecomment-1836075934) myself and am hoping to hear back from the creators.

That said, the only reason I release a 0.0.2 is because I needed to update the readme. So there are no changes. In the future, depending on the answer I get in the other issue, I will consider upgrade paths as I release new versions. I definitely understand that being able to upgrade without data loss is a requirement.

**Comment by imor** [comment]
We are still working on the docs but there should be a lot of answered question in the discussion in supabase/dbdev#164

**Comment by point-source** [comment]
Thanks @imor. I'm going to close this now that there is documentation in the other issue and since I now have a concrete plan to support upgrades without data loss once pg_tle is updated.
