### ISSUE TITLE
Supabase impersonation bypasses RLS rules that depends on this package

### ISSUE THREAD

**Issue by gregor-vatworx** [point-source/supabase-tenant-rbac#15]
can you give an concrete example of an RLS implementation for a sample table using the is_group_member & jwt_is_group_member functions?
I would like to try this with the new impersonation feature within the supabase dashboard to no avail.
thx.

**Comment by point-source** [comment]
As I was working on creating some examples for you, I noticed that the impersonation feature was not correctly working with this package. As it turns out, this appears to be a bug in supabase and as such, I have reported it: https://github.com/supabase/supabase/issues/20452

Once this is resolved, you will better be able to test this package as it relates to RLS policies. Until then, do not rely on the impersonation feature to accurately show what RLS is doing while using this package. You can use api calls instead to test. It is certainly less convenient but is the only option that we have until the bug is fixed, short of modifying this package itself to work around it.

**Comment by point-source** [comment]
I have a preliminary fix for this that I am working on in the [1.0.0](https://github.com/point-source/supabase-tenant-rbac/tree/1.0.0) branch

**Comment by point-source** [comment]
This is now fixed as of 1.0.0
