### ISSUE TITLE
Questions about RBAC and its table collection

### ISSUE THREAD

**Issue by alka7ex** [point-source/supabase-tenant-rbac#17]
Hi 

New here in supabase, right now i'm building supabase with sveltekit for internal dashboard. i'm very thanked by your contributions 

I have several questions, sorry it a bit dumb questions
1. `{"groups":{"72ad5253-0c61-4407-9504-12a0b8e33be7":["admin"]},"provider":"email","providers":["email"]}` i see that the metadata is changed as expected, but what is the points of having dedicated table for `groups`? which is just an id and name, and what is the `name` for?
2. what is the use of the `group_user`? is that a table to tell which roles user have?
3. i see there is new role table, but it is not related with any other table that generated by `supabase-tenant-rbac`
4. there is `user_roles`, what is the usage of it?

**Comment by point-source** [comment]
Great questions. Here you go:

1. Your implication is correct. Technically, groups do not need names. You could leave this blank if you want. That said, I personally find names to be easier to distinguish as a human than uuids. Also, at least for my use-cases, there are parts of my app that display the the group to users that belong to it. Especially when users belong to multiple groups. In those cases, it's better for me to display the group name in the UI instead of the group ID. As for the existence of the group table itself, that is because it is far easier to manage groups in a table vs directly in the metadata of all users. For example, you may want certain groups to be able to create/delete groups themselves and in those cases, you would not want to give those users your supabase service key (which is necessary to modify metadata in the auth.users table) because that is a massive security risk. So by restricting group modification to a triggered table, you can appropriately scope permissions for who can manage groups.
2. Correct. group_user is a mapping of users to groups. It is the source of truth for who belongs in each group and what role they hold in that group. Just like with the groups table, it is the securable interface through which group memberships are modified because modifying the metadata directly would be either difficult, error-prone, and insecure or all of the above.
3. A new role table? The only tables that should be created by this package are: groups, group_users, user_roles (view). Anything beyond those three is either a bug or is unrelated to this package and came from elsewhere.
4. The user_roles view is actually a view rather than a table and is really just a select/join between the groups, group_users, and auth.users tables. It is for convenience so that you can easily see user names and emails next to groups next to roles. It doesn't do much beyond that. You are welcome to use it however you like.

EDIT: If this answered your questions, please close this issue. Otherwise, feel free to keep asking and I'll do my best to clarify. Thanks for using this package!

**Comment by alka7ex** [comment]
Hi @point-source thank you for answering my question, however i still have a follow up questions

1. what is your use case using group and filling the name? any example?
2. so i have a profiles table, can i use profiles table for the group_user?

sorry i still didn't get the group concepts for this, is groups is like a roles?

**Comment by point-source** [comment]
In my case, group is being used similar to tenant. Imagine you were creating a Slack clone. You have multiple slack workspaces. Each workspace has multiple users. Each user has a role or multiple roles. In this case, the workspace would be the group, the users would be the users in the group, and the roles would be permissions and channel membership.

My own application is similar. Any user can create a group which is a collection of users that each have a role within the group and can act on group resources in specific ways based on their role in the group. Users can be members of multiple groups and have different roles in each group. So userA can create groupBlue and add userB to it as a read-only viewer. UserB can create groupGreen and add userC to is as an admin. UserC could then use their admin access to add userA to groupGreen if they wish but would not be able to see the presence of groupBlue.

At the end of the day, you can use it however you want. If you only need users and roles, then just ignore groups. Create a single group that everyone goes in and just assign them roles as needed. Not every application is multi-tenant.

As for the profiles table, are you maintaining a separate table of profile data that is different than the built-in auth.users table that comes with supabase? Or are you using this in something other than supabase? How do you envision making use of the profiles table with this project? What is the use-case / what behavior are you looking for?

**Comment by alka7ex** [comment]
if i dont need multitenancy or groups, it is better for me to get rid of it because it became redundant or should i leave as it is?

for the profiles table i maintain separate table of profile data from the built in auth.users table, this profile data is for the full_name, address, things that i can't do it in the auth.users table

so for the profile, basically i create a functions where if there is a user created, it will creating new records in profiles table

**Comment by point-source** [comment]
Well it's pretty tightly integrated so you couldn't really remove it without having to re-write most all the functionality. That said, it's really easy to ignore. Just create one single group and use that group ID any time a group ID is required.

As for the profiles, if your profiles table uses the same user ID as the auth table does, then you don't need to do anything special since the user_roles table already links back to the auth.users table. However, I should point out that `user_metadata` field is for the purpose of storing things such as name, address, etc. So you technically don't need a separate table for this. I do not use one myself but I do store that additional info. More info here: https://supabase.com/docs/guides/auth/auth-user-management#the-user-object

**Comment by alka7ex** [comment]
Hi @point-source 

Got it, yeah i've seen it and will be quite complex if i want to remove it, and i will just ignore it

for the profiles, so basically questions is if i relocate the group_users role column to profiles table. the reason is because i already have profile anyway, and right now in profiles, everytime the there is new user created in auth.users i already have a functionality to automatically create the profiles in profiles table.

but in the group_users that functionality seems not there.

so the options is 2
1. relocate the role column to profile
2. make the group_users is automatically created when the auth.users have new user. (although i prefered the options number 1 since it's only needs single table)

**Comment by point-source** [comment]
> relocate the role column to profile

This would be a similar amount of work as removing the group functionality since any function that references that table or column would have to change. I'm not trying to dissuade you from that however. You are welcome to take and use any code in this repository however you see fit, per the license. I just can't really provide support or updates for custom implementations.

> make the group_users is automatically created when the auth.users have new user. (although i prefered the options number 1 since it's only needs single table)

This would be the most compatible with this package and the most future-proof in terms of updates. But I agree that having two/three separate tables is non-ideal.

I'm not sure of a way to work around this easily. It would be nice if when the TLE is installed, one could specify which tables they want to use. But then that puts the requirement on the installer to ensure the structure remains consistent and intact and eventually leads to non-deterministic updates. So unless someone far more experienced in SQL than I knows a solution that I do not, I'm not sure there's much that can be done here to solve your specific case.

You might want to just make a fork of this repository and modify it for your own use-case. Then, when I push updates, you can try to manually merge them if they are useful to you.

**Comment by multiplehats** [comment]
Can I just say that it's amazing that you give these lengthy detailed responses @point-source? Kudo's 👏

**Comment by alka7ex** [comment]
@point-source ahh i see ok then, i will keep as it is for now

thank you for your help
