### ISSUE TITLE
Updating an existing `group_users` does not remove old data from raw_app_meta_data

### ISSUE THREAD

**Issue by fnimick** [point-source/supabase-tenant-rbac#3]
Either `group_users` should be made explicitly insert- and delete- only (restrict update), or `update_user_roles()` should take this into account.

To duplicate:
- create two users
- create a group
- assign one user to the group; confirm that this user has had `raw_app_meta_data` updated
- change the `group_users` entry to point to the other user
- confirm that now both users are marked as group members in `raw_app_meta_data`

**Comment by point-source** [comment]
That's correct. The original intent here was that `group_users` would not be updated since changing a user_id would be revoking a role from one user and adding to another. It felt more correct to delete/insert and seemed unlikely to occur in a single step. Also, it invalidates the creation timestamp on the role record which seems bad since it is a sort of audit of when the role was granted to the user.

I can certainly modify the function to support updating but it feels a bit wrong vs preventing updating. Thoughts?
